[build]
builder = "NIXPACKS"

[deploy]
healthcheckPath = "/"
healthcheckTimeout = 60
healthcheckInterval = 30
healthcheckGracePeriod = 90
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[build.env]
PYTHON_VERSION = "3.11"

[deploy.env]
ENVIRONMENT = "production"
PORT = "8000" 