[build]
builder = "NIXPACKS"

[deploy]
healthcheckPath = "/"
healthcheckTimeout = 10
healthcheckInterval = 15
healthcheckGracePeriod = 30
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[build.env]
PYTHON_VERSION = "3.11"

[deploy.env]
ENVIRONMENT = "production"
PORT = "8000" 