[build]
builder = "DOCKERFILE"

[deploy]
healthcheckPath = "/api/v1/health"
healthcheckTimeout = 30
healthcheckInterval = 60
healthcheckGracePeriod = 60
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5

[deploy.env]
ENVIRONMENT = "production"
PORT = "8000"
# 메모리 최적화 설정
PYTHONUNBUFFERED = "1"
PYTHONDONTWRITEBYTECODE = "1"
# uvicorn 메모리 최적화
WEB_CONCURRENCY = "1" 